baseurl: "http://verric.github.io/"
languageCode: "en-GB"
title: "<Insert Title Here>"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
canonifyurls: true
theme: "herring-cove"


params:
  ProfilePicture: "~/pictures/rotated_again.png"
  enableLandingPage: true
  landingPageRedirectUrl: "/about/"
  AuthorName: "Richiez"
